language: php

php:
  - 7.1
  - 7.2

dist: trusty
sudo: true

install: 
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg
  - composer install --no-interaction --prefer-source

script: phpunit --verbose