language: php

php:
  - 7.1
  - 7.2

env:
  APP_ENV: testing
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_DRIVER: sync
  DB_CONNECTION: sqlite
  BROADCAST_DRIVER: log

branches:
  - master

install: 
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - composer test

script:
  - phpunit